# Generated by Django 4.2.1 on 2024-01-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signup_day',
            field=models.CharField(default=18, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='signup_month',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='signup_year',
            field=models.CharField(default=2024, max_length=50),
        ),
    ]
