# Generated by Django 4.2.1 on 2023-06-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_user_signup_day_user_signup_month_user_signup_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signup_day',
            field=models.CharField(default=10, max_length=50),
        ),
    ]
