# Generated by Django 4.2.1 on 2023-06-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_user_fromgoogle_user_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='signup_day',
            field=models.CharField(default=16, max_length=50),
        ),
    ]
