# Generated by Django 4.2.1 on 2023-12-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signup_day',
            field=models.CharField(default=21, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='signup_month',
            field=models.CharField(default=12, max_length=50),
        ),
    ]
