# Generated by Django 4.2.1 on 2023-12-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_alter_user_signup_day_alter_user_signup_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fromGoogle',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_blocked',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='signup_day',
            field=models.CharField(default=23, max_length=50),
        ),
    ]
