# Generated by Django 4.2.1 on 2023-06-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='phone',
        ),
    ]
