# Generated by Django 4.2.1 on 2023-06-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0002_remove_adminuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='signup_day',
            field=models.CharField(default=10, max_length=50),
        ),
    ]
