# Generated by Django 4.2.1 on 2023-06-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0004_alter_adminuser_signup_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='signup_day',
            field=models.CharField(default=15, max_length=50),
        ),
    ]
