# Generated by Django 4.2.1 on 2023-06-21 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0006_alter_adminuser_signup_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='signup_day',
            field=models.CharField(default=21, max_length=50),
        ),
    ]
