# Generated by Django 4.2.1 on 2023-06-22 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_alter_user_signup_day'),
        ('AdminSide', '0007_alter_adminuser_signup_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='signup_day',
            field=models.CharField(default=22, max_length=50),
        ),
        migrations.CreateModel(
            name='Notifivcation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('type', models.CharField(max_length=255, verbose_name='Type')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('notification_day', models.CharField(default=22, max_length=50)),
                ('notification_month', models.CharField(default=6, max_length=50)),
                ('notification_year', models.CharField(default=2023, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.user')),
            ],
        ),
    ]
