# Generated by Django 4.2.1 on 2023-06-22 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0011_remove_notification_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
