# Generated by Django 4.2.1 on 2023-12-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0012_delete_adminuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_day',
            field=models.CharField(default=21, max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_month',
            field=models.CharField(default=12, max_length=50),
        ),
    ]
