# Generated by Django 4.2.1 on 2023-12-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0013_alter_notification_notification_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_day',
            field=models.CharField(default=23, max_length=50),
        ),
    ]
