# Generated by Django 4.2.1 on 2023-06-12 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WasteCategory', '0002_rename_wastename_biowaste_name'),
        ('Address', '0001_initial'),
        ('Account', '0004_alter_user_signup_day'),
        ('WasteBooking', '0002_rename_wasteorderdetail_wastepickdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='WastePickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('pickup_status', models.CharField(default='pending', max_length=20)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('note', models.TextField()),
                ('pickup_day', models.IntegerField(default=12)),
                ('pickup_month', models.IntegerField(default=6)),
                ('pickup_year', models.IntegerField(default=2023)),
                ('is_ordered', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Address.address')),
                ('biowaste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WasteCategory.wastecategory')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='wastepickdetail',
            name='wastebooking',
        ),
        migrations.DeleteModel(
            name='WasteBooking',
        ),
        migrations.AddField(
            model_name='wastepickdetail',
            name='wastepickup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WasteBooking.wastepickup'),
            preserve_default=False,
        ),
    ]
