# Generated by Django 4.2.1 on 2023-06-12 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WasteBooking', '0003_wastepickup_remove_wastepickdetail_wastebooking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastepickdetail',
            name='wastepickup',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='WasteBooking.wastepickup'),
        ),
    ]
