# Generated by Django 4.2.1 on 2023-06-12 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WasteBooking', '0004_alter_wastepickdetail_wastepickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastepickdetail',
            name='wastepickup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WasteBooking.wastepickup'),
        ),
    ]
