# Generated by Django 4.2.1 on 2023-06-14 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_user_signup_day'),
        ('Address', '0001_initial'),
        ('WasteCategory', '0002_rename_wastename_biowaste_name'),
        ('WasteBooking', '0006_rename_note_wastepickup_notes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WastePickDetail',
            new_name='WastePickupDetail',
        ),
    ]
