# Generated by Django 4.2.1 on 2023-06-15 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WasteBooking', '0007_rename_wastepickdetail_wastepickupdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wastepickup',
            old_name='pickup_status',
            new_name='status',
        ),
    ]
