# Generated by Django 4.2.1 on 2023-06-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteBooking', '0008_rename_pickup_status_wastepickup_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastepickup',
            name='pickup_day',
            field=models.IntegerField(default=16),
        ),
    ]
