# Generated by Django 4.2.1 on 2023-06-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WasteCategory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biowaste',
            old_name='wastename',
            new_name='name',
        ),
    ]
