# Generated by Django 4.2.1 on 2023-06-04 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
        ('Address', '0001_initial'),
        ('ScrapCategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('note', models.TextField()),
                ('is_ordered', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Address.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.user')),
                ('scrapwaste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScrapCategory.scrapcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrap_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pickup_date', models.DateField(default=None)),
                ('pickup_time', models.TimeField(default=None)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], max_length=50)),
                ('address', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Address.address')),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Account.user')),
                ('wastebooking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScrapBooking.scrapbooking')),
            ],
        ),
    ]
