# Generated by Django 4.2.1 on 2023-06-06 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScrapCategory', '0001_initial'),
        ('ScrapBooking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraporderdetail',
            name='scrapwaste',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ScrapCategory.scrapcategory'),
            preserve_default=False,
        ),
    ]
