# Generated by Django 4.2.1 on 2023-06-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_user_signup_day_user_signup_month_user_signup_year'),
        ('ScrapCategory', '0002_rename_scrapname_scrapwaste_name'),
        ('Address', '0001_initial'),
        ('ScrapBooking', '0003_rename_wastebooking_scraporderdetail_scrapbooking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScrapOrderDetail',
            new_name='ScrapPickupDetail',
        ),
    ]
