# Generated by Django 4.2.1 on 2023-06-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScrapBooking', '0005_scrappickup_remove_scrappickupdetail_scrapbooking_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrappickup',
            old_name='note',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='scrappickup',
            name='weight',
        ),
        migrations.AddField(
            model_name='scrappickup',
            name='scrap_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='scrappickup',
            name='pickup_day',
            field=models.IntegerField(default=15),
        ),
    ]
