# Generated by Django 4.2.1 on 2023-12-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScrapBooking', '0010_alter_scrappickup_pickup_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrappickup',
            name='pickup_day',
            field=models.IntegerField(default=23),
        ),
    ]
